apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic1
  namespace: reportportal
  labels:
    app: elastic
    type: local 
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 30Gi
  accessModes: [ "ReadWriteOnce" ] 
  hostPath:
    path: "/mnt"
